# Generated by Django 6.0.6 on 2026-07-09 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.TextField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='images.png', upload_to='profile')),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('experience_level', models.CharField(choices=[('BG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('PROF', 'Professional')], default='BG', max_length=150)),
                ('preferred_market', models.CharField(choices=[('fx', 'Forex'), ('cyp', 'Cypto'), ('stc', 'Stocks'), ('ind', 'Indices'), ('comm', 'Commodities')], default='fx', max_length=150)),
                ('favourite_pair', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('account_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_per_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('daily_loss_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('daily_profit_target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('connection_type', models.CharField(choices=[('mn', 'manual'), ('mt5', 'MT5')], default='mn', max_length=150)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreakModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('position_price', models.IntegerField(default=0)),
                ('stop_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('take_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('risk_reward_ratio', models.CharField(default=0)),
                ('leverage', models.CharField(max_length=100)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('potential_reward', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_outcome', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_outcome', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('op', 'Open'), ('cl', 'Closed'), ('be', 'Breakeven')], max_length=100)),
                ('result', models.CharField(choices=[('w', 'win'), ('cl', 'loss'), ('be', 'BE')], max_length=100)),
                ('setup', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=5)),
                ('session', models.CharField(max_length=100)),
                ('entry_date', models.CharField(max_length=100)),
                ('trade_notes', models.TextField(blank=True, default='', null=True)),
                ('emotion_before', models.CharField(max_length=100)),
                ('emotion_during', models.CharField(max_length=100)),
                ('emotion_after', models.CharField(max_length=100)),
                ('lesson_learned', models.TextField(blank=True, default='', null=True)),
                ('news_checked', models.BooleanField(default=False)),
                ('followed_confirmation', models.BooleanField(default=False)),
                ('risk_under_one_percent', models.BooleanField(default=False)),
                ('avoided_revenge_trade', models.BooleanField(default=False)),
                ('avoided_fomo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeScreenShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='screenshot')),
                ('caption', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot', to='account.trade')),
            ],
        ),
    ]
