# Generated by Django 6.0.6 on 2026-07-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_badge_profile_streakmodel_trade_tradescreenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streakmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tradescreenshot',
            name='trade',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='StreakModel',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeScreenShot',
        ),
    ]
