# Generated by Django 6.0.6 on 2026-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_country_alter_profile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
