# Generated by Django 6.0.6 on 2026-07-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='followed_plan',
            field=models.BooleanField(default=False),
        ),
    ]
