# Generated by Django 6.0.6 on 2026-07-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_trade_followed_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='position_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_percent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.CharField(max_length=100),
        ),
    ]
