# Generated by Django 6.0.6 on 2026-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_trade_result_alter_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
