# Generated by Django 6.0.6 on 2026-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_trade_entry_price_alter_trade_exit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
