# Generated by Django 6.0.6 on 2026-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_trade_stop_loss_alter_trade_take_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='risk_reward_ratio',
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_per_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
