# Generated by Django 6.0.6 on 2026-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_remove_trade_risk_reward_ratio_trade_risk_per_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='risk_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_percent',
            field=models.CharField(max_length=100),
        ),
    ]
