# Generated by Django 6.0.6 on 2026-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_trade_risk_amount_alter_trade_risk_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='actual_outcome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='expected_outcome',
            field=models.CharField(max_length=100),
        ),
    ]
