# Generated by Django 6.0.6 on 2026-07-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_trade_actual_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradescreenshot',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_screenshot', to='trading.trade'),
        ),
    ]
