# Generated by Django 6.0.6 on 2026-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_tradescreenshot_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit_and_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
